"""
Individual report exporters — Phase 4.1

Each exporter receives a ProjectBundle and returns a GeneratedReport.
All exporters are pure functions — no I/O, no DB calls.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from export_engine.schemas import (
    ExportFormat,
    GeneratedFile,
    GeneratedReport,
    ProjectBundle,
    ReportSection,
    ReportType,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _heading(text: str, level: int = 2) -> str:
    return f"{'#' * level} {text}\n"


def _bullet_list(items: List[str]) -> str:
    if not items:
        return "_None_\n"
    return "\n".join(f"- {i}" for i in items) + "\n"


def _code_block(code: str, lang: str = "") -> str:
    return f"```{lang}\n{code}\n```\n"


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _safe(val: Any, default: str = "_Not provided_") -> str:
    if val is None:
        return default
    s = str(val).strip()
    return s if s else default


# ---------------------------------------------------------------------------
# README exporter
# ---------------------------------------------------------------------------

def export_readme(bundle: ProjectBundle) -> GeneratedReport:
    """Generate project README.md from bundle."""
    meta = bundle.metadata
    pm = bundle.get_agent_output_json("project_manager")
    ba = bundle.get_agent_output_json("business_analyst")
    dev = bundle.get_agent_output_json("devops_engineer")

    lines = [
        f"# {meta.title}\n",
        f"> Generated by CodeForge AI · {_now()}\n",
        "",
        f"## Overview\n",
        f"{_safe(meta.description, pm.get('project_summary', '_No description available._'))}\n",
        "",
    ]

    # Goals
    goals = pm.get("goals", [])
    if goals:
        lines.append("## Goals\n")
        lines.append(_bullet_list(goals))
        lines.append("")

    # Tech stack
    arch = bundle.get_agent_output_json("solution_architect")
    endpoints = arch.get("endpoints", [])
    if endpoints:
        lines.append("## API Endpoints\n")
        for ep in endpoints[:8]:
            lines.append(f"- `{ep.get('method','GET')} {ep.get('path','')}` — {ep.get('description','')}")
        lines.append("")

    # Deployment
    deployment_guide = dev.get("deployment_guide", "")
    if deployment_guide:
        lines.append("## Quick Start\n")
        lines.append(deployment_guide[:800])
        lines.append("")

    # Generated files summary
    if bundle.generated_files:
        lines.append("## Generated Files\n")
        for f in bundle.generated_files[:20]:
            lines.append(f"- `{f.path}`")
        lines.append("")

    lines.append(f"---\n_Generated by CodeForge AI on {_now()}_\n")

    return GeneratedReport(
        report_type=ReportType.README,
        filename="README.md",
        content="\n".join(lines),
    )


# ---------------------------------------------------------------------------
# Architecture Report
# ---------------------------------------------------------------------------

def export_architecture(bundle: ProjectBundle) -> GeneratedReport:
    arch = bundle.get_agent_output_json("solution_architect")
    pm   = bundle.get_agent_output_json("project_manager")

    lines = [
        "# Architecture Report\n",
        f"> {bundle.metadata.title} · Generated {_now()}\n\n",
        "## System Overview\n",
        f"{_safe(pm.get('project_summary'))}\n\n",
        "## Scope\n",
        f"{_safe(pm.get('project_scope'))}\n\n",
    ]

    # File structure
    file_structure = arch.get("file_structure", [])
    if file_structure:
        lines.append("## Project File Structure\n")
        lines.append(_code_block("\n".join(file_structure), ""))
        lines.append("")

    # DB Schema
    db_schema = arch.get("db_schema", [])
    if db_schema:
        lines.append("## Database Schema\n")
        for table in db_schema:
            tname = table.get("table", "unknown")
            cols = table.get("columns", [])
            lines.append(f"### `{tname}`\n")
            for col in cols:
                fk = f" → {col.get('references')}" if col.get('is_fk') else ""
                lines.append(f"- `{col.get('name')}` ({col.get('type')}){fk}")
            lines.append("")

    # Endpoints summary
    endpoints = arch.get("endpoints", [])
    if endpoints:
        lines.append("## API Endpoints Summary\n")
        lines.append("| Method | Path | Auth | Description |")
        lines.append("|--------|------|------|-------------|")
        for ep in endpoints:
            auth = "✅" if ep.get("requires_auth") else "❌"
            lines.append(f"| {ep.get('method','')} | `{ep.get('path','')}` | {auth} | {ep.get('description','')} |")
        lines.append("")

    # Risks
    risks = pm.get("risks", [])
    if risks:
        lines.append("## Risks\n")
        lines.append(_bullet_list(risks))

    return GeneratedReport(
        report_type=ReportType.ARCHITECTURE,
        filename="Architecture_Report.md",
        content="\n".join(lines),
    )


# ---------------------------------------------------------------------------
# API Documentation
# ---------------------------------------------------------------------------

def export_api_docs(bundle: ProjectBundle) -> GeneratedReport:
    api = bundle.get_agent_output_json("api_designer")

    lines = [
        "# API Documentation\n",
        f"> {bundle.metadata.title} · Generated {_now()}\n\n",
    ]

    # Auth flow
    auth_flow = api.get("authentication_flow", {})
    if auth_flow:
        lines.append("## Authentication\n")
        lines.append(f"**Method:** {_safe(auth_flow.get('method'))}\n")
        lines.append(f"**Token Endpoint:** `{_safe(auth_flow.get('token_endpoint'))}`\n")
        lines.append(f"**Refresh Endpoint:** `{_safe(auth_flow.get('refresh_endpoint'))}`\n")
        lines.append(f"{_safe(auth_flow.get('description'))}\n\n")

    # Versioning
    lines.append(f"**Versioning Strategy:** {_safe(api.get('versioning_strategy'))}\n\n")

    # Endpoints
    endpoints = api.get("endpoints", [])
    if endpoints:
        lines.append("## Endpoints\n")
        for ep in endpoints:
            auth = " 🔒" if ep.get("auth_required") else ""
            lines.append(f"### `{ep.get('method','')} {ep.get('path','')}`{auth}\n")
            lines.append(f"{_safe(ep.get('summary'))}\n")
            if ep.get("request_model"):
                lines.append(f"**Request Model:** `{ep['request_model']}`\n")
            if ep.get("response_model"):
                lines.append(f"**Response Model:** `{ep['response_model']}`\n")
            errors = ep.get("error_responses", [])
            if errors:
                lines.append(f"**Error Responses:** {', '.join(errors)}\n")
            lines.append("")

    # Request models
    req_models = api.get("request_models", [])
    if req_models:
        lines.append("## Request Models\n")
        for m in req_models:
            lines.append(f"### `{m.get('name','')}`\n")
            fields = m.get("fields", [])
            for f in fields:
                if isinstance(f, dict):
                    lines.append(f"- `{f.get('name','')}`: {f.get('type','')} — {f.get('description','')}")
            lines.append("")

    # OpenAPI spec
    openapi = api.get("openapi_spec", "")
    if openapi:
        lines.append("## OpenAPI Specification\n")
        lines.append(_code_block(openapi[:2000], "yaml"))

    return GeneratedReport(
        report_type=ReportType.API_DOCS,
        filename="API_Documentation.md",
        content="\n".join(lines),
    )


# ---------------------------------------------------------------------------
# Database Schema
# ---------------------------------------------------------------------------

def export_database_schema(bundle: ProjectBundle) -> GeneratedReport:
    db = bundle.get_agent_output_json("database_engineer")
    arch = bundle.get_agent_output_json("solution_architect")

    lines = [
        "# Database Schema\n",
        f"> {bundle.metadata.title} · Generated {_now()}\n\n",
    ]

    # Detailed schema
    schema_details = db.get("db_schema_details", "")
    if schema_details:
        lines.append("## Schema Details\n")
        lines.append(schema_details + "\n\n")

    # SQLAlchemy models
    models_code = db.get("sqlalchemy_models_code", "")
    if models_code:
        lines.append("## SQLAlchemy Models\n")
        lines.append(_code_block(models_code, "python"))

    # Indexes
    indexes = db.get("indexes", [])
    if indexes:
        lines.append("## Indexes\n")
        lines.append("| Name | Table | Columns | Unique |")
        lines.append("|------|-------|---------|--------|")
        for idx in indexes:
            unique = "✅" if idx.get("unique") else "❌"
            cols = ", ".join(idx.get("columns", []))
            lines.append(f"| {idx.get('name','')} | {idx.get('table','')} | {cols} | {unique} |")
        lines.append("")

    # Relationships
    rels = db.get("relationships", [])
    if rels:
        lines.append("## Relationships\n")
        for r in rels:
            lines.append(f"- **{r.get('name','')}**: `{r.get('from_table','')}` → `{r.get('to_table','')}` ({r.get('cardinality','')})")
        lines.append("")

    # Migration plan
    migration_plan = db.get("migration_plan", [])
    if migration_plan:
        lines.append("## Migration Plan\n")
        lines.append(_bullet_list(migration_plan))

    # Normalization
    norm = db.get("normalization_review", "")
    if norm:
        lines.append("## Normalization Review\n")
        lines.append(norm + "\n")

    return GeneratedReport(
        report_type=ReportType.DATABASE_SCHEMA,
        filename="Database_Schema.md",
        content="\n".join(lines),
    )


# ---------------------------------------------------------------------------
# ER Diagram
# ---------------------------------------------------------------------------

def export_er_diagram(bundle: ProjectBundle) -> GeneratedReport:
    db = bundle.get_agent_output_json("database_engineer")
    ba = bundle.get_agent_output_json("business_analyst")

    lines = [
        "# ER Diagram\n",
        f"> {bundle.metadata.title} · Generated {_now()}\n\n",
    ]

    # Mermaid diagram from database engineer
    mermaid = db.get("er_diagram_mermaid", "")
    if mermaid:
        lines.append("## Entity Relationship Diagram\n")
        lines.append(_code_block(mermaid, "mermaid"))

    # Entities from business analyst
    entities = ba.get("entities", [])
    rels = ba.get("relationships", [])
    if entities and not mermaid:
        lines.append("## Entities (Mermaid ERD)\n")
        mermaid_lines = ["erDiagram"]
        for entity in entities:
            name = entity.get("name", "Entity")
            fields = entity.get("fields", [])
            mermaid_lines.append(f"  {name} {{")
            for field in fields:
                mermaid_lines.append(f"    string {field}")
            mermaid_lines.append("  }")
        for rel in rels:
            from_ = rel.get("from_", "A")
            to = rel.get("to", "B")
            rtype = rel.get("type", "has")
            mermaid_lines.append(f'  {from_} ||--o{{ {to} : "{rtype}"')
        lines.append(_code_block("\n".join(mermaid_lines), "mermaid"))

    # Entities list
    if entities:
        lines.append("## Entity List\n")
        for entity in entities:
            name = entity.get("name", "")
            fields = entity.get("fields", [])
            lines.append(f"### {name}\n")
            lines.append(_bullet_list(fields))

    return GeneratedReport(
        report_type=ReportType.ER_DIAGRAM,
        filename="ER_Diagram.md",
        content="\n".join(lines),
    )


# ---------------------------------------------------------------------------
# Agent Execution Report
# ---------------------------------------------------------------------------

def export_agent_execution(bundle: ProjectBundle) -> GeneratedReport:
    lines = [
        "# Agent Execution Report\n",
        f"> {bundle.metadata.title} · Generated {_now()}\n\n",
        "## Pipeline Summary\n",
        f"**Project:** {bundle.metadata.title}\n",
        f"**Status:** {bundle.metadata.status}\n",
        f"**Total Agents:** {len(bundle.agent_outputs)}\n\n",
    ]

    # Pipeline order
    PIPELINE_ORDER = [
        "project_manager", "business_analyst", "product_owner",
        "solution_architect", "database_engineer", "api_designer",
        "backend_developer", "security_engineer", "qa_engineer",
        "frontend_developer", "code_reviewer", "documentation_writer",
        "devops_engineer",
    ]

    completed = sum(1 for a in bundle.agent_outputs if a.status == "completed")
    failed    = sum(1 for a in bundle.agent_outputs if a.status == "failed")
    lines.append(f"**Completed:** {completed} | **Failed:** {failed}\n\n")

    # Per-agent details
    lines.append("## Agent Details\n")
    lines.append("| Agent | Status | Exec Time | Retries | Files |")
    lines.append("|-------|--------|-----------|---------|-------|")

    agent_map = {a.agent_name: a for a in bundle.agent_outputs}
    for agent_name in PIPELINE_ORDER:
        a = agent_map.get(agent_name)
        if a:
            status_icon = {"completed": "✅", "failed": "❌", "running": "⏳", "skipped": "⏭️"}.get(a.status, "❓")
            exec_time = f"{a.execution_time_seconds:.1f}s" if a.execution_time_seconds else "—"
            files = len(a.generated_files)
            lines.append(f"| {agent_name.replace('_', ' ').title()} | {status_icon} {a.status} | {exec_time} | {a.retry_count} | {files} |")
        else:
            lines.append(f"| {agent_name.replace('_', ' ').title()} | ⏭️ skipped | — | 0 | 0 |")
    lines.append("")

    # Detailed output per agent
    lines.append("## Agent Outputs\n")
    for agent_name in PIPELINE_ORDER:
        a = agent_map.get(agent_name)
        if not a:
            continue
        lines.append(f"### {agent_name.replace('_', ' ').title()}\n")
        lines.append(f"**Status:** {a.status}  ")
        if a.error_message:
            lines.append(f"**Error:** {a.error_message}\n")
        if a.output_json:
            # Show a brief summary — first 3 keys
            keys = list(a.output_json.keys())[:3]
            for k in keys:
                val = a.output_json[k]
                if isinstance(val, str):
                    lines.append(f"**{k}:** {val[:200]}\n")
                elif isinstance(val, list):
                    lines.append(f"**{k}:** {len(val)} items\n")
        lines.append("")

    return GeneratedReport(
        report_type=ReportType.AGENT_EXECUTION,
        filename="Agent_Execution_Report.md",
        content="\n".join(lines),
    )


# ---------------------------------------------------------------------------
# Security Report
# ---------------------------------------------------------------------------

def export_security(bundle: ProjectBundle) -> GeneratedReport:
    sec = bundle.get_agent_output_json("security_engineer")

    lines = [
        "# Security Report\n",
        f"> {bundle.metadata.title} · Generated {_now()}\n\n",
    ]

    overall_risk = sec.get("overall_risk", "unknown")
    risk_icon = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}.get(overall_risk, "⚪")
    lines.append(f"## Overall Risk: {risk_icon} {overall_risk.upper()}\n\n")

    # Counts
    lines.append("## Finding Summary\n\n")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    lines.append(f"| 🔴 Critical | {sec.get('critical_count', 0)} |")
    lines.append(f"| 🟠 High | {sec.get('high_count', 0)} |")
    lines.append(f"| 🟡 Medium | {sec.get('medium_count', 0)} |")
    lines.append(f"| 🟢 Low | {sec.get('low_count', 0)} |")
    lines.append("")

    # JWT assessment
    jwt = sec.get("jwt_assessment", "")
    if jwt:
        lines.append("## JWT Assessment\n")
        lines.append(jwt + "\n\n")

    # Findings
    findings = sec.get("findings", [])
    if findings:
        lines.append("## Security Findings\n")
        for f in findings:
            sev = f.get("severity", "info")
            sev_icon = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}.get(sev, "⚪")
            lines.append(f"### {sev_icon} {f.get('title', 'Finding')}\n")
            lines.append(f"**Category:** {f.get('category', '')}  ")
            if f.get("owasp_id"):
                lines.append(f"**OWASP:** {f['owasp_id']}  ")
            if f.get("file"):
                loc = f":{f['line']}" if f.get("line") else ""
                lines.append(f"**File:** `{f['file']}{loc}`  ")
            lines.append(f"\n{f.get('description', '')}\n")
            lines.append(f"**Recommendation:** {f.get('recommendation', '')}\n")
            snippet = f.get("code_snippet", "")
            if snippet:
                lines.append(_code_block(snippet, "python"))
            lines.append("")

    # OWASP coverage
    owasp = sec.get("owasp_coverage", [])
    if owasp:
        lines.append("## OWASP Coverage\n")
        lines.append(_bullet_list(owasp))

    # Patches
    patches = sec.get("recommended_patches", [])
    if patches:
        lines.append("## Recommended Patches\n")
        for i, patch in enumerate(patches, 1):
            lines.append(f"{i}. {patch}")
        lines.append("")

    return GeneratedReport(
        report_type=ReportType.SECURITY,
        filename="Security_Report.md",
        content="\n".join(lines),
    )


# ---------------------------------------------------------------------------
# Testing Report
# ---------------------------------------------------------------------------

def export_testing(bundle: ProjectBundle) -> GeneratedReport:
    qa = bundle.get_agent_output_json("qa_engineer")

    lines = [
        "# Testing Report\n",
        f"> {bundle.metadata.title} · Generated {_now()}\n\n",
    ]

    test_plan = qa.get("test_plan", "")
    if test_plan:
        lines.append("## Test Plan\n")
        lines.append(test_plan + "\n\n")

    # Coverage
    coverage = qa.get("estimated_coverage", 0.0)
    lines.append(f"## Estimated Test Coverage: {coverage:.0f}%\n\n")
    lines.append(f"> {qa.get('coverage_report_summary', '')}\n\n")

    # Edge cases
    edge_cases = qa.get("edge_cases", [])
    if edge_cases:
        lines.append("## Edge Cases\n")
        lines.append("| Name | Type | Description |")
        lines.append("|------|------|-------------|")
        for tc in edge_cases:
            lines.append(f"| {tc.get('name','')} | {tc.get('type','')} | {tc.get('description','')} |")
        lines.append("")

    # Unit tests code
    unit_code = qa.get("unit_tests_code", "")
    if unit_code:
        lines.append("## Unit Tests\n")
        lines.append(_code_block(unit_code[:2000], "python"))

    return GeneratedReport(
        report_type=ReportType.TESTING,
        filename="Testing_Report.md",
        content="\n".join(lines),
    )


# ---------------------------------------------------------------------------
# Deployment Guide
# ---------------------------------------------------------------------------

def export_deployment_guide(bundle: ProjectBundle) -> GeneratedReport:
    devops = bundle.get_agent_output_json("devops_engineer")

    lines = [
        "# Deployment Guide\n",
        f"> {bundle.metadata.title} · Generated {_now()}\n\n",
    ]

    guide = devops.get("deployment_guide", "")
    if guide:
        lines.append("## Deployment Instructions\n")
        lines.append(guide + "\n\n")

    # Env vars
    env_vars = devops.get("production_env_vars", [])
    if env_vars:
        lines.append("## Environment Variables\n")
        lines.append("| Variable | Description | Default | Secret |")
        lines.append("|----------|-------------|---------|--------|")
        for ev in env_vars:
            secret = "🔒" if ev.get("is_secret") else ""
            default = ev.get("default_value", "—") or "—"
            lines.append(f"| `{ev.get('name','')}` | {ev.get('description','')} | {default} | {secret} |")
        lines.append("")

    # Dockerfile
    dockerfile = devops.get("dockerfile", "")
    if dockerfile:
        lines.append("## Dockerfile\n")
        lines.append(_code_block(dockerfile, "dockerfile"))

    # Docker Compose
    compose = devops.get("docker_compose", "")
    if compose:
        lines.append("## Docker Compose\n")
        lines.append(_code_block(compose, "yaml"))

    # GitHub Actions
    gha = devops.get("github_actions_workflow", "")
    if gha:
        lines.append("## GitHub Actions CI/CD\n")
        lines.append(_code_block(gha, "yaml"))

    # Nginx
    nginx = devops.get("nginx_config", "")
    if nginx:
        lines.append("## Nginx Configuration\n")
        lines.append(_code_block(nginx, "nginx"))

    return GeneratedReport(
        report_type=ReportType.DEPLOYMENT_GUIDE,
        filename="Deployment_Guide.md",
        content="\n".join(lines),
    )


# ---------------------------------------------------------------------------
# Version Report
# ---------------------------------------------------------------------------

def export_version(bundle: ProjectBundle) -> GeneratedReport:
    lines = [
        "# Version Report\n",
        f"> {bundle.metadata.title} · Generated {_now()}\n\n",
        "## Project Version History\n\n",
    ]

    if bundle.version_history:
        lines.append("| Version | Agent | Artifact Type | Timestamp |")
        lines.append("|---------|-------|---------------|-----------|")
        for entry in bundle.version_history[:50]:
            lines.append(
                f"| v{entry.get('version','')} "
                f"| {entry.get('agent_name','')} "
                f"| {entry.get('artifact_type','')} "
                f"| {entry.get('timestamp','')[:19]} |"
            )
        lines.append("")
    else:
        lines.append("_No version history available._\n\n")

    # Generated files list
    if bundle.generated_files:
        lines.append("## Generated Files\n\n")
        lines.append("| File Path | Language |")
        lines.append("|-----------|----------|")
        for f in bundle.generated_files:
            lines.append(f"| `{f.path}` | {f.language} |")
        lines.append("")

    return GeneratedReport(
        report_type=ReportType.VERSION,
        filename="Version_Report.md",
        content="\n".join(lines),
    )


# ---------------------------------------------------------------------------
# Memory Report
# ---------------------------------------------------------------------------

def export_memory_report(bundle: ProjectBundle) -> GeneratedReport:
    lines = [
        "# Memory Report\n",
        f"> {bundle.metadata.title} · Generated {_now()}\n\n",
        f"**Total Memory Records:** {len(bundle.memory_records)}\n\n",
    ]

    if bundle.memory_records:
        # Group by artifact type
        by_type: Dict[str, int] = {}
        for rec in bundle.memory_records:
            at = rec.get("metadata", {}).get("artifact_type", "unknown") if isinstance(rec.get("metadata"), dict) else "unknown"
            by_type[at] = by_type.get(at, 0) + 1

        lines.append("## Memory by Artifact Type\n\n")
        lines.append("| Artifact Type | Count |")
        lines.append("|---------------|-------|")
        for at, count in sorted(by_type.items(), key=lambda x: -x[1]):
            lines.append(f"| {at} | {count} |")
        lines.append("")

        # Sample records
        lines.append("## Sample Memory Records\n\n")
        for rec in bundle.memory_records[:5]:
            doc = rec.get("document", "")[:200]
            meta = rec.get("metadata", {})
            at = meta.get("artifact_type", "") if isinstance(meta, dict) else ""
            lines.append(f"**{at}:** {doc}...\n")
    else:
        lines.append("_No memory records found._\n\n")

    return GeneratedReport(
        report_type=ReportType.MEMORY_REPORT,
        filename="Memory_Report.md",
        content="\n".join(lines),
    )


# ---------------------------------------------------------------------------
# RAG Context Report
# ---------------------------------------------------------------------------

def export_rag_report(bundle: ProjectBundle) -> GeneratedReport:
    lines = [
        "# RAG Context Report\n",
        f"> {bundle.metadata.title} · Generated {_now()}\n\n",
        f"**Total RAG Contexts Used:** {len(bundle.rag_context_used)}\n\n",
    ]

    if bundle.rag_context_used:
        lines.append("## RAG Context Entries\n\n")
        for i, ctx in enumerate(bundle.rag_context_used[:10], 1):
            query = ctx.get("query", "")
            results = ctx.get("results", [])
            lines.append(f"### Context {i}: `{query}`\n")
            lines.append(f"**Results retrieved:** {len(results)}\n")
            for r in results[:3]:
                doc = r.get("document", "")[:150] if isinstance(r, dict) else str(r)[:150]
                score = r.get("similarity_score", 0.0) if isinstance(r, dict) else 0.0
                lines.append(f"- (score={score:.3f}) {doc}\n")
            lines.append("")
    else:
        lines.append("_No RAG context data recorded._\n\n")

    return GeneratedReport(
        report_type=ReportType.RAG_REPORT,
        filename="RAG_Context_Report.md",
        content="\n".join(lines),
    )


# ---------------------------------------------------------------------------
# Registry — map ReportType → exporter function
# ---------------------------------------------------------------------------

EXPORTER_REGISTRY = {
    ReportType.README:           export_readme,
    ReportType.ARCHITECTURE:     export_architecture,
    ReportType.API_DOCS:         export_api_docs,
    ReportType.DATABASE_SCHEMA:  export_database_schema,
    ReportType.ER_DIAGRAM:       export_er_diagram,
    ReportType.AGENT_EXECUTION:  export_agent_execution,
    ReportType.SECURITY:         export_security,
    ReportType.TESTING:          export_testing,
    ReportType.DEPLOYMENT_GUIDE: export_deployment_guide,
    ReportType.VERSION:          export_version,
    ReportType.MEMORY_REPORT:    export_memory_report,
    ReportType.RAG_REPORT:       export_rag_report,
}
