"""add generated_files column to projects

Revision ID: a22a770042b6
Revises: 631b2a18d5d9
Create Date: 2026-07-04 16:06:17.182208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a22a770042b6'
down_revision: Union[str, None] = '631b2a18d5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('generated_files', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'generated_files')
    # ### end Alembic commands ###
